### ISSUE TITLE
No feedback for ADDRESS_REQUEST denied?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#103]
If an endpoint sends a polite ADDRESS_REQUEST that is well formed but the receiver can't or won't action it, there's no feedback.  Since capsules are sent reliably, we can depend on them making it to the peer, but not necessarily being procesed. If the request is blackholed, should it, for example, ever be retried? There's a difference between a proxy refusing to do something and it temporarily being unable to do it (possibly due to resource constraints or rate limiting).

**Comment by achernya** [comment]
I don't think we currently have support for an ADDRESS_REQUEST capsule not being replied-to. The current language is written with the expectation that every REQUEST gets a RESPONSE. SO I would expect that if the request cannot be satisfied (i.e., is rejected) you get the rejection response that @tfpauly just committed.

So I would expect a proxy that is being rate-limited to respond, just slowly.

**Comment by LPardue** [comment]
Thanks! #96 makes it clearer how to assertively respond, which is good. However, the text

> Upon receiving the ADDRESS_REQUEST capsule, an endpoint SHOULD assign one or more
IP addresses to its peer, and then respond with an ADDRESS_ASSIGN capsule to inform
the peer of the assignment.

This SHOULD is a bit hairy. Maybe it would be clear to split these out and state that a receiver of an ADDRESS_REQUEST MUST reply.

**Comment by achernya** [comment]
I agree, I think that this should be upgraded to MUST that was missed after request/response IDs were added.

**Comment by DavidSchinazi** [comment]
Agreed. I'd be supportive of a MUST along the lines of:
> The recipient of an Address Request MUST reply with an Assigned Address that can either be the address requested, or another valid address, or the all-zero address to indicate the request was rejected.

Though we need to wordsmith it better

**Comment by mirjak** [comment]
Not sure if a MUST really helps here. I guess there is no way to force an endpoint to reply and we also can't specify until when the reply needs to come, so you always need to implement a logic to detect that you didn't get reply.

To be honest that also a point where I'm not fully happy with #96. So far my assumption was rather that you can of course nicely ask for an address. But as soon as you get an address_assign you should assume that the list is complete and work with rather that than speculatively waiting for a potentially update that may or may not come. Sending a reject as specified in #96 makes the situation less ambiguous but in the end it shouldn't really change much because it always better to start sending quickly with an address that you got assigned than to wait and hope for another address.

**Comment by achernya** [comment]
> I guess there is no way to force an endpoint to reply

Why not? Peer could reset the stream, or time out the entire connection. That is what the point of a MUST is.

**Comment by mirjak** [comment]
If you get a bunch of addresses assigned that you don't want to use and they're decide to not use the connect, I guess you should close it. however, if you use it, there is no point in closing it just because you didn't get a reply to your request. And again we don't send when a reply should or must be send. So there is no final deadline when you could close a stream.

**Comment by achernya** [comment]
The whole reason we added request IDs was to remove the requirement to timeout. This does not work if we allow the peers to simply not respond. The contract here needs to be that reach request gets a response, like HTTP. If a peer breaks that, you close the stream -- like HTTP.

**Comment by mirjak** [comment]
I don't think it's the same. If you send two requests which each one IP address and you only get one reply, you can use the IP you got and everything is fine. In http if you don't get a reply, you connection simply broken.

Yes, it would make things easier if you can guarantee that you always get a reply but I don't think there is a good way to enforce that; or even trying to enforce it, creates more limitation than it might help.

**Comment by LPardue** [comment]
I think its easier to built a client if it knows whether to expect responses in the protocol or not. This will govern how it approaches cases where it does or does not get a timely response, for some measure of timely. These might be (and probably are) implementations choices that should be pointed out. There's lots of reasons a client might _detect_ something was slow, when in fact it was serviced as fast as possible.

Imagine I run a proxy that might, for reasons that are outside of its control, have delays servicing one address request out of a few. If clients are going to be "smart" and make opaque decisions, then it could adversely affect my operations.
