### ISSUE TITLE
ICMP contradiction

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-ip#113]
Over email, Mike Bishop mentioned:
> Section 4.6.3 says ICMP is always allowed, but 4.5 does not mention this when describing the scope of a requested tunnel

When looking into this I noticed that the [ROUTE_ADVERTISEMENT Capsule](https://ietf-wg-masque.github.io/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#name-route_advertisement-capsule) section states the following about the IP Protocol field:
> ICMP traffic is always allowed, regardless of the value of this field.

But the [Error Signalling](https://ietf-wg-masque.github.io/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#name-error-signalling) section states:
>  If an endpoint sends ROUTE_ADVERTISEMENT capsules, its routes SHOULD include an allowance for receiving ICMP messages.

This is contradictory. I would recommend removing the recommendation in Error Signalling.

**Comment by achernya** [comment]
I don't think this is contradictory. The former text says "we will send you traffic whether you like it or not". The latter says "you should do something useful with it". Certainly it could be wordsmithed a bit, but I don't think an outright removal is a good idea as we should still give guidance to users that they are expected to do something if they're doing ipproto-based routing.

**Comment by DavidSchinazi** [comment]
That doesn't match my understanding. To me, the former says "you don't need to send a route with ip_proto=ICMP because it's always allowed" but the latter says "you SHOULD send a route with ip_proto=ICMP"

**Comment by achernya** [comment]
I think those are compatible? The former is saying you don't have to, the latter is signaling you've acknowledged and will do something useful with it.

**Comment by DavidSchinazi** [comment]
Isn't that just wasted bytes?

**Comment by achernya** [comment]
I could imagine a server doing something useful with this information. Maybe having different ratelimits for ICMP traffic for a well-behaved client that will process the messages.

But this only applies in the cases where you're using ipproto scoping, so I am not too worried about the bytes-wasted

**Comment by DavidSchinazi** [comment]
If we intend to have recipients act on this information, we should clearly define what it's meant to convey, otherwise we'll create interoperability issues.

**Comment by achernya** [comment]
That's fair. To be clear, I do not object to removing the text as you originally suggested. I just wanted to clarify that I didn't consider the current situation a contradiction.

**Comment by gloinul** [comment]
I think we need to clarify this a bit as it actually exist three different interpretation depending on what was requested.

So if the requester do a Connect request with ip_proto=1 scope:
I will get all ICMP message for this IP address would be my interpretation. This is fine to ask for, but I think we need a security consideration note on this. This should only be allowed if this external IP address that is assigned is only used by this requesting endpoint. Otherwise it will allow some possibility to overhead what the other endpoint attempt to do when ICMP messages are generated back towards this IP address. 

So if the connect request is for ip_proto=6  (TCP):
In this case we have two interpretations of what has been written. 
A) The IP proxy will send ICMP messages to the requesting endpoint to indicate issues.
B) The IP proxy will match any incoming ICMP messages on the external IP address assgined and forward them to the requestor.

So what I expect to happen is that A) will always happen, but it is unclear if B) will happen. 
I think we want to make clear that B) MAY/SHOULD/MUST be done. 

I will write a PR for the security consideration for requesting ICMP traffic for an assigned address.
