### ISSUE TITLE
IPv6 handling question...

### ISSUE THREAD

**Issue by vparla** [ietf-wg-masque/draft-ietf-masque-connect-ip#114]
It seems that the IPv6 doesn't offer an option to fragment the inner IP packet as an alternative to not passing the IPv6 packet if it does not meet MTU requirements.  Has an alternative approach that allows fragmentation of the inner packet been considered here?  Could a client and server perhaps negotiate this capability to allow for fragmentation of IPv4/6 packets that would exceed the MTU requirements?

**Comment by vparla** [comment]
IPv6 supports limited fragmentation using optional headers.  Routers are not allowed to fragment, but sources are.  This means that in an IPv6 Proxying implementation, it would be perfectly legal to perform IPv6 fragmentation at the source / destination.
https://www.rfc-editor.org/rfc/rfc8200#section-4.5

**Comment by achernya** [comment]
CONNECT-IP generally is not a source, it is a router.

**Comment by vparla** [comment]
CONNECT-IP is a method on proxying from an endpoint (the source) to a proxy.  It is not an intermediary router.

**Comment by achernya** [comment]
Not necessarily. It could be an intermediary. And even then it is an intermediary if it's connect to a TAP/TUN device, where the kernel is the source. We do not expect most users to be producing IP frames directly. If you yourself are doing that, then you are free to fragment, but CONNECT-IP will not do it for you.

**Comment by vparla** [comment]
It think you are conflating the language of the RFC with the intent.  Routing is this context is an intermediary not a logical routing function on the same device.

**Comment by achernya** [comment]
I disagree. The same device is not a meaningful property. I can have lots of VRFs or network namespaces or different IP stacks. We have no knowledge of this at the CONNECT-IP protocol level.

**Comment by vparla** [comment]
I think this is short sighted and I would not be in favor of a specification with this type of limitation in it that doesn't have a way to negotiate this type of capability.

**Comment by achernya** [comment]
There's no oversight here -- you can easily add this negotiation in an extension.

**Comment by vparla** [comment]
apologies in advance, I may have missed it in the family of MASQUE specifications, what is the facility to create a custom extension that could be easily proposed as a standard to enable type of capability.  Would it be a custom capsule or did you have something else in mind here?

**Comment by DavidSchinazi** [comment]
Hi Vinny, we discussed fragmentation with regards to this draft [earlier in the process](https://github.com/ietf-wg-masque/draft-ietf-masque-connect-ip/issues/45), and the decision reached was that we would not support it but make sure that it would be possible to add as an extension. With the current draft, it'll actually be quite easy to add, because of the way HTTP Datagrams ([RFC 9297](https://www.rfc-editor.org/rfc/rfc9297.html)) were designed: HTTP Datagrams can either be sent with QUIC DATAGRAM frames (which are limited by the MTU of the outer QUIC connection) or with DATAGRAM capsules (which are sent on streams and can be split up). It would be very easy to create an extension that defines a new `Please-Fragment-My-Packets` HTTP header and when both sides negotiate it, they decide to take large packets and send them using the DATAGRAM capsule instead of dropping them. I encourage you to write such an extension draft if you're interested in this functionality, because we are currently in the process of [revising the MASQUE charter](https://mailarchive.ietf.org/arch/msg/masque/Hzq6NOUOOXcoSL3iX6t0togoRbk/) to allow working on extensions. I'm closing this issue since we don't need to make any changes to this draft to support such an extension, and I'll happily review the extension draft when it appears.
