### ISSUE TITLE
How should the client deal with assigned addresses changing or getting removed?

### ISSUE THREAD

**Issue by jhatala** [ietf-wg-masque/draft-ietf-masque-connect-ip#121]
>If an ADDRESS_ASSIGN capsule does not contain an address that was previously transmitted in another ADDRESS_ASSIGN capsule, that indicates that the address has been removed. An ADDRESS_ASSIGN capsule can also be empty, indicating that all addresses have been removed.

What is the expectation that the client does when its assignments change, or when it loses all addresses altogether?  It makes sense that the spec is unambiguous about the meaning of the messages, but an empty ADDRESS_ASSIGN capsule seems like a dead-end for the stream to me.  Does it make sense for a spec-compliant client to have to deal with getting renumbered?  What would be a use-case for that?  The IP Proxy leasing IPs from a DHCP server?  Privacy Extensions for IPv6?

**Comment by tfpauly** [comment]
For a typical client-to-server remote access use case, the client probably wants to have addresses at all times in order to use the tunnel.

However, there are other use cases (point to point VPNs, etc) where it would be reasonable to temporarily go down to no addresses, and wait for assignments to come up later.

**Comment by jhatala** [comment]
Ok, that makes sense, thank you!
