### ISSUE TITLE
Editorial: add a Performance Considerations section

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-ip#145]
Bob [mentioned](https://mailarchive.ietf.org/arch/msg/masque/ScXl6_FeeeIAJPvTZoqnIUT1YT4/) that we should discuss performance more in this document. I propose we add a Performance Considerations section based on [the one in CONNECT-UDP](https://www.rfc-editor.org/rfc/rfc9298#name-performance-considerations)

**Comment by gloinul** [comment]
I will note that the ECN considerations for IP are different from them in UDP. 

If one disable congestion control and the outer QUIC connection will ignore the ECN marks then one MAY handle tunneled in datagram IP packets by copying the ECN bits from inner to outer and then one MUST recombine them in the egress using the rules in RFC 6040. 

If one doesn't disable congestion control in the QUIC connection then one MUST NOT copy the ECN field, Instead if the tunneled traffic enables ECN it can be either just ignored, or if one has an ingress QUEUE to the tunnel one MAY mark packets with CE rather than dropping them.

**Comment by achernya** [comment]
I don't think it's that simple. You can't copy the ECN bits if there are multiple packets in separate datagram frames coalesced into the same QUIC packet.
