### ISSUE TITLE
Mandate usage of HTTPS

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#163]
From Joe Touch review:

It should also address the potential use of HTTP-level encryption (e.g., TLS,
DTLS) to protect the tunnel contents and tunnel configuration exchanges.

 We require the scheme to be https, which means that QUIC or TLS is mandatory.

I see that in the examples, but it doesn’t appear to be a requirement anywhere. Can you indicate where it explains that “[http://…”](https://protect2.fireeye.com/v1/url?k=31323334-501d5122-313273af-454445555731-c4adc279bc355fbe&q=1&e=93c74e8e-16d0-455d-b2e4-e65598f856d7&u=http%3A%2F%2F...-9o0a%2F) would be considered invalid or that ONLY “https” can be used to start?

MW: I think Joe is correct that this is only implicit required when using HTTP/3. We don’t actually have a requirement to use HTTPS.

**Comment by DavidSchinazi** [comment]
Oh you're right, the use of the https scheme isn't actually mandated. That said, we shouldn't mandate use of HTTPS, since there can be other future schemes. Instead we should RECOMMEND running HTTP over TLS or QUIC to provide confidentiality, integrity, and authentication. Given the existence of HTTP intermediaries, there will be scenarios where the client-to-intermediary security is provided by QUIC and the intermediary-to-proxy security is provided by other mechanisms such as IPsec or proprietary hardware-offloaded security.

**Comment by gloinul** [comment]
I agree fully with the RECOMMEND path. That sounds all correct.
