### ISSUE TITLE
Ask for two, get one

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-masque/draft-ietf-masque-connect-ip#73]
ADDRESS_ASSIGN, aside from being too many characters to type, is apparently now cumulative.  There is also no direct tie to ADDRESS_REQUEST, which is also too many characters to type.

ADDRESS_ASSIGN can also be spontaneous.

Take the case where the client asks for two addresses, but only gets one.  How does the client distinguish between this being a spontaneous assignment or a response to its request.  If it is spontaneous, it might want to keep waiting in case the server will eventually give it the other address that it asked for.

This is not a great situation for clients.

**Comment by DavidSchinazi** [comment]
I agree. I think the simplest fix is to add a request ID. I've written that up as PR #74.

**Comment by mirjak** [comment]
I don't think I see a problem here. If you can an assignment is really doesn't matter to which request it belongs. There are only two cases: you get the assignment and the assignment works for you and you can start sending. Or you get an assignment which doesn't work for you and you can't start sending. In this second case, you can either wait and then close the connection or you can try a few times to send an address request again.

Let's take this one example that maybe could make sense here: you ask for an IPv6 address but you get an IPv4 address. Either this doesn't work for you because you or the other end doesn't support IPv4. Or it works for you and I don't really see a benefit to wait any longer. I guess if you ever get an IPv6 address in future, you can still switch or even send your request again depending on the application. But why would you wait and simply delay your request?

**Comment by DavidSchinazi** [comment]
> I don't think I see a problem here. If you can an assignment is really doesn't matter to which request it belongs. There are only two cases: you get the assignment and the assignment works for you and you can start sending. Or you get an assignment which doesn't work for you and you can't start sending. In this second case, you can either wait and then close the connection or you can try a few times to send an address request again.

That's exactly the problem. "wait" here means a timeout as opposed to an explicit failure signal. Timeouts open up new classes of problems such as timing out too soon (and breaking an otherwise functional connection) or too late (and causing user-visible delays).

> Let's take this one example that maybe could make sense here: you ask for an IPv6 address but you get an IPv4 address. Either this doesn't work for you because you or the other end doesn't support IPv4. Or it works for you and I don't really see a benefit to wait any longer. I guess if you ever get an IPv6 address in future, you can still switch or even send your request again depending on the application. But why would you wait and simply delay your request?

[Happy Eyeballs](https://www.rfc-editor.org/rfc/rfc8305.html#section-3) suggests waiting longer if all you have is IPv4. This can of technique is common if you have reason to believe IPv6 works better than IPv4.

**Comment by DavidSchinazi** [comment]
From @tfpauly on the [corresponding PR](https://github.com/ietf-wg-masque/draft-ietf-masque-connect-ip/pull/74):
> Yeah, this does make things simple. Probably better to do this than to be "clever" and not need it.
