### ISSUE TITLE
How should we NAK an ADDRESS_REQUEST?

### ISSUE THREAD

**Issue by asedeno** [ietf-wg-masque/draft-ietf-masque-connect-ip#95]
I've been noodling a bunch of scenarios where I think the draft could use a bit more clarification, and maybe a rev of the wire format around Request IDs for `ADDRESS_REQUEST` / `ADDRESS_ASSIGN`. They largely fall under the question of _how does an endpoint NAK an address request?_ The draft says an endpoint receiving an `ADDRESS_REQUEST` capsule **SHOULD** respond with an `ADDRESS_ASSIGN` capsule, so I suppose not responding is allowed, but figuring out how to respond with a NAK is worthwhile.

For this, I'm going to use the term client to refer to the party requesting addresses/prefixes, and server to refer to the party assigning addresses/prefixes.

---
1)
The client has received an (unsolicited?) address.
The client then requests a different address.
The server has chosen to not assign that address.

A suggestion I've heard: server sends `ADDRESS_ASSIGN` capsule with existing assignment and new request's Request ID.

---
2)
The client sends a capsule requesting multiple addresses
The server has chosen to only assign a subset of those addresses (or a different address).

Using the suggestion from (1) involves replying with sufficiently many `ADDRESS_ASSIGN` capsules so as to exhaust the Request IDs sent. Maybe this means sending back n capsules all with the same one assignment, or n/2 capsules with the same two assignments, etc?

---
3)
The client sends a capsule requesting an IP version not supported by the server.

This could be a request for addresses for IPv4 and IPv6 from a server that supports only one, or a simpler case of asking for an IPv4 address from an IPv6-only server.

It feels odd to use the suggestion from (1) to respond to a request for an IPv4 address with an IPv6 address or vice versa.

---
An alternative, which requires a wire format revision, is to include a list of NAK'd Request IDs in the `ADDRESS_ASSIGN` capsule, which could be as simple as a varint count of IDs, followed by that many more varints. In the happy path, this is just one extra `00` byte in the capsule.

**Comment by DavidSchinazi** [comment]
Thanks for filing this @asedeno. I agree that the draft isn't currently clear enough on how to respond to these scenarios. The three options I see are:
1. do nothing
2. write some text to explain how to use the existing capsule formats to indicate a rejected address request
3. add a list of rejected request IDs to the ADDRESS_ASSIGN capsule

Of these I think we really should avoid (1) because that could lead to interoperability issues, but I'm ok with either (2) or (3). I think I prefer (3) because changing the wire format now isn't too high of a cost and I think it'll make the protocol more explicit.

**Comment by tfpauly** [comment]
I agree we should do something here. Between (2) and (3), I'm not sure.

We could fairly easily just say that if you include an `Assigned Address` with a non-zero Request ID but the assigned address is all zeros with a prefix length of 32 or 128, you're assigning an empty address, which is a rejection. Arguably, client must handle receiving such a capsule response anyway, and treat it as "no address assigned for that request". This is option (2), I think.

If we do something like option (3), we'd have a field in the main ADDRESS_ASSIGN capsule for a list of rejected IDs, which would likely need to have a length in front, so we'd now have a field of at least a byte in all ADDRESS_ASSIGN capsules (even ones with no rejections) to handle the possibility of rejections.

We either have a case where a lot of rejections leads to a somewhat bloated capsule, but the happy cases are nice and concise, or a case that optimizes for lots of rejections and always adds a byte to the happy cases. I personally prefer (2) there, since it only gets ugly if a ton of requests are being made anyhow.

Thoughts @DavidSchinazi ?

**Comment by DavidSchinazi** [comment]
I like your proposal @tfpauly, if we add text saying that 0.0.0.0/32 and ::/128 mean "your request was rejected" then we get the explicit property without changing the wire format. That works for me.

**Comment by tfpauly** [comment]
It's also good because it doesn't have two ways of saying the same thing, since we'll need to handle 0.0.0.0/32 and ::/128 anyhow. I can try to write that up.

**Comment by asedeno** [comment]
I appreciate the added symmetry that comes from giving the zero addresses specific meaning in both requests and assignments, and no wire format changes + no ambiguity is a win. LGTM.
